#!/usr/bin/env bash

for i in "$@"
do
case $i in
    -v=*|--version=*)
    VERSION="${i#*=}"
    shift # past argument=value
    ;;
esac
done

echo "$VERSION"

git add .
git commit -m "Some message" --quiet
echo $VERSION
git push -u origin main --quiet
echo $VERSION
git tag $VERSION
git push --tags

